name: Are 0 Tickets available?

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/6 0-3,7-23 * * *'
  push:
    branches: main

jobs:
  initAndCheck:
    name: Init and Check for Tickets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm i
      - name: Run Check
        run: npm test
